name: Build and release

on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./SourceCode/AgOpenGPS.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  # Runtime to publish for (Windows 64-bit)
  PUBLISH_RUNTIME: win-x64

  # Path to the output folder
  PUBLISH_DIR: ./AgOpenGPS

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.3.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v4.1.0
      with:
        updateProjectFiles: true

    - name: Install dependencies
      run: dotnet restore --runtime ${{env.PUBLISH_RUNTIME}} ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: dotnet build --no-restore ${{env.SOLUTION_FILE_PATH}}

    - name: Test
      run: dotnet test --no-restore --no-build ${{env.SOLUTION_FILE_PATH}}

    - name: Publish
      run: dotnet publish --no-restore --configuration ${{env.BUILD_CONFIGURATION}} --runtime ${{env.PUBLISH_RUNTIME}} ${{env.SOLUTION_FILE_PATH}}

    - name: Create AgOpenGPS.zip
      shell: powershell
      run: Compress-Archive -Path "${{env.PUBLISH_DIR}}" -Destination "AgOpenGPS.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ env.GitVersion_SemVer }}
        tag_name: ${{ env.GitVersion_SemVer }}
        body: |
          Automated Release by GitHub Action CI
        draft: ${{ github.ref_name == 'master' }}
        prerelease: ${{ contains(github.ref_name, 'release/') }}
        files: AgOpenGPS.zip
